### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by Gaurav2728** [asanghi/serial_preference#9]
Steps to reproduce the bug:-

**Ruby 2.4.1**
**Rails 4.2.1**

Add `preferences` column to users table.
```
class AddPreferencesToUser < ActiveRecord::Migration
  def self.up
    add_column :users, :preferences, :text
  end

  def self.down
    remove_column :users, :preferences, :text
  end
end
```

Add rake task in migration to populate data for preferences column
```
class PopulateUserPreferences < ActiveRecord::Migration
  def change
    Rake::Task['user:populate_preferences'].invoke
  end
end
```

user_preferences.rake
```
namespace :user do
  desc 'Populate user preferences data'
  task populate_preferences: :environment do
    users = User.all
    users.each do |user|
      user.update_attributes(default: user.country.id, verified: true)
    end
  end
end
```

Error logs
```
undefined method `[]' for nil:NilClass
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/serial_preference-1.2.1/lib/serial_preference/has_preference_map.rb:69:in `write_preference_attribute'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/serial_preference-1.2.1/lib/serial_preference/has_preference_map.rb:41:in `block (2 levels) in build_preference_definitions'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/attribute_assignment.rb:54:in `public_send'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/attribute_assignment.rb:35:in `each'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/persistence.rb:251:in `block in update'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/transactions.rb:220:in `transaction'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/Users/gaurav/.rvm/gems/ruby-2.4.1@rails4/gems/activerecord-4.2.9/lib/active_record/persistence.rb:250:in `update'
```

**Comment by asanghi** [comment]
How are preferences defined in user model?

**Comment by Gaurav2728** [comment]
```
preferences do
      integer :default_country, default: 1
      boolean :verified, default: true
      .....
end
```
